name: Release

on:
  push:
    tags:
    - v*.*.*
env:
  PREPERATION_COMMIT: '[github-actions.ci] auto update version in `CITATION.cff`'

jobs:
  check-preperation:
    runs-on: ubuntu-latest
    outputs:
      prepared: ${{ steps.check-preperation.outputs.prepared }}  # Define the boolean output as 'is-valid'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Expected: '${{ env.PREPERATION_COMMIT }}'"
          echo "Received: '$COMMIT_MESSAGE'"

          if [[ "$COMMIT_MESSAGE" != "${{ env.PREPERATION_COMMIT }}" ]]; then
            prepared="false"
          else
            prepared="true"
          fi

          echo "prepared: $prepared" >> $GITHUB_OUTPUT
  
  update-version:
    name: Update version in CITATION.cff
    needs: [check-preperation]
    if: ${{ needs.check-preperation.outputs.prepared == 'false' }}
    runs-on: ubuntu-latest
    steps:
    - name: Generate token for PyPSA Bot
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.PYPSA_BOT_ID }}
        private-key: ${{ secrets.PYPSA_BOT_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for setuptools_scm
        ref: master
        token: ${{ steps.generate-token.outputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - run: pip install toml setuptools_scm
    - run: echo ${{ github.ref_name }}
    - run: |
        import re
        from setuptools_scm import get_version

        # Fetch version number
        version = get_version()

        # Read CITATION.cff file
        with open('CITATION.cff', 'r') as file:
            cff_content = file.read()

        # Update the version in the .cff file
        updated_cff_content = re.sub(r"(?<=version: ).+(?= #)",version,cff_content,flags=re.MULTILINE)

        # Write the updated content back to the CITATION.cff file
        with open('CITATION.cff', 'w') as file:
            file.write(updated_cff_content)
      shell: python

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: '${{ env.PREPERATION_COMMIT }}'
        add: 'CITATION.cff'
        tag: '${{ github.ref_name }} --force'
        tag_push: '--force'

  build:
    # Build the Python SDist and wheel, performs metadata and readme linting
    name: Build and verify package
    needs: [check-preperation]
    if: ${{ needs.check-preperation.outputs.prepared == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hynek/build-and-inspect-python-package@v2

  release:
    # Publish a GitHub release from the given git tag
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: softprops/action-gh-release@v2
      with:
        body: |
          Revised release notes are available in the [documentation](https://pypsa.readthedocs.io/en/latest/references/release-notes.html).
        append_body: true
        generate_release_notes: true

  # publish:
  #   # Publish the built SDist and wheel from "dist" job to PyPI
  #   name: Publish to PyPI
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/project/pypsa/
  #   permissions:
  #     id-token: write
  #   steps:
  #   - uses: actions/download-artifact@v4
  #     with:
  #       name: Packages
  #       path: dist
  #   - uses: pypa/gh-action-pypi-publish@release/v1

