name: Unit tests
# Subsequent workflow of Tests/ test.yaml workflow

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
      python-versions:
        type: string
        required: true

# Cancel any in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit
  cancel-in-progress: true

jobs:
  unit-tests:
    name: "${{ matrix.python-version }} | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        os:
        - ubuntu
        - macos
        - windows
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for setuptools_scm

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install macos dependencies
      if: matrix.os == 'macos'
      run: |
        brew update
        # pkg-config is deprecated but still installed in runner
        # Can be removed once it is removed from the runner
        brew unlink pkg-config@0.29.2 || true
        brew install hdf5

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: dist

    - name: Install package and dependencies
      run: |
        python -m pip install uv
        uv pip install --compile --system "$(ls dist/*.whl)[dev,hdf5]"

    - name: Run unit tests # Also includes doctests
      if: matrix.os != 'windows' || matrix.python-version != '3.13'
      run: |
        coverage run -m pytest
        coverage xml

    - name: Test with pytest (windows & Python 3.13)
      if: matrix.os == 'windows' && matrix.python-version == '3.13'
      run: |
        coverage run -m pytest
        coverage xml
        return 0

    - name: Upload code coverage report
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

