name: Tests

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  pull_request:
    branches:
    - '**'
  schedule:
  - cron: "0 5 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    # Build the Python SDist and wheel, performs metadata and readme linting
    name: Build and verify package
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Needed for setuptools_scm
    - uses: hynek/build-and-inspect-python-package@v2
      id: baipp

    outputs:
      artifact-name: ${{ steps.baipp.outputs.artifact-name }}
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}

  unit-tests:
    name: Unit
    needs: [build]
    uses: ./.github/workflows/test-unit.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      python-versions: ${{ needs.build.outputs.python-versions }}

  integration-tests:
    name: Integration
    needs: [build]
    uses: ./.github/workflows/test-integration.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}

  checks:
    name: Checks
    needs: [build]
    uses: ./.github/workflows/test-checks.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
